### ISSUE TITLE
列表Dialog实现数据字典功能的疑问？

### ISSUE THREAD

**Issue by zhengxiaochuan** [694551594/android-dialog#2]
针对数据字典的这种场景，我要使用ListDialog，显示的是文字，使用其对应的code值，这种情况怎么来做？

**Comment by 694551594** [comment]
构建ListDiaolog的时候可以传Object的对象，然后toString()方法返回的内容就是显示到对话框上的内容。在对话框相关事件的回调里面，可以拿到之前传入的Object对象，然后就可以拿到你的code了。稍后给你上个例子。

**Comment by 694551594** [comment]
final List<DialogChoiceItem> items =
                        DialogChoiceItems.instance()
                                .add(0, "标记为已读", !isUserMessage && unread)
                                .add(1, "标记为未读", !isUserMessage && !unread)
                                .add(2, "删除", !isSystemMessage && isUserMessage)
                                .getItems();
                return DialogBuilder.listDialog(getContext()).setChoiceItems(items)
                        .setOnChoiceListener(new DialogBuilder.OnChoiceListener() {
                            @Override
                            public void onChoiceItem(int index, Object item) {
                                switch (DialogChoiceItem.getItemId(item)) {
                                    case 0:
                                        updateMessageStatus(messageEntity, 2);
                                        break;
                                    case 1:
                                        updateMessageStatus(messageEntity, 1);
                                        break;
                                    case 2:
                                        deleteMessage(messageEntity);
                                        break;
                                }
                            }
                        }).create();

**Comment by zhengxiaochuan** [comment]
DialogChoiceItems这个类是你自定义的类吗，能不能让我看一下这个类是怎么写的啊？

**Comment by 694551594** [comment]
这个类相当于你的字典类。这个地方你只做参考，具体的你还得按照你的业务来写：
public class DialogChoiceItem {
    private int id;
    private String title;

    public static DialogChoiceItem make(int id, String title) {
        DialogChoiceItem item = new DialogChoiceItem();
        item.id = id;
        item.title = title;
        return item;
    }

    public static DialogChoiceItem of(Object o) {
        return (DialogChoiceItem) o;
    }

    public static int getItemId(Object o) {
        return of(o).getId();
    }

    public int getId() {
        return id;
    }

    @Override
    public String toString() {
        return title;
    }
}

public class DialogChoiceItems {
    private List<DialogChoiceItem> items = new ArrayList<>();

    public static DialogChoiceItems instance() {
        return new DialogChoiceItems();
    }

    public DialogChoiceItems add(DialogChoiceItem item, boolean flag) {
        if (flag) {
            items.add(item);
        }
        return this;
    }

    public DialogChoiceItems add(int id, String title, boolean flag) {
        if (flag) {
            items.add(DialogChoiceItem.make(id, title));
        }
        return this;
    }

    public List<DialogChoiceItem> getItems() {
        return items;
    }
}

**Comment by zhengxiaochuan** [comment]
我明白了，主要就是List<Object>里面Object类的toString()方法。已经解决了，谢谢了

**Comment by 694551594** [comment]
嗯  好的，不客气。
